### ISSUE TITLE
RAML 0.8 types (named parameters) support?

### ISSUE THREAD

**Issue by jstoiko** [raml-org/typesystem-ts#81]
I'd like to use `raml-org/typesystem-ts` for validation of both RAML 0.8 types (previously ["named parameters"](https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md#named-parameters)) and RAML 1.0 data types. 

I've run some tests and it works fine but maybe I'm overlooking something. Is it same to use it for RAML 0.8 type-validation?

**Comment by petrochenko-pavel-a** [comment]
It should work fine for most of cases, but I remember at least one situation when it will not work. typesystem-ts - does not support original raml 0.8 `date` time from scratch. @KonstantinSviridov please correct me if I am wrong. However it should be easy to fix.

**Comment by sichvoge** [comment]
The question is if this implementation should be able to validate named parameters from 0.8 as well. I know it might be easy to bring in, but I would actually question why. IMHO, the typesystem has been introduced in RAML 1.0 and should only allow the validation on that specification.

**Comment by sichvoge** [comment]
Lets close this since I am against to support RAML 0.8 in our RAML 1.0 type system.
