### ISSUE TITLE
Provide a way (or document how) to resolve json-schema $ref

### ISSUE THREAD

**Issue by jstoiko** [raml-org/typesystem-ts#82]
It seems like raml-typesystem is capable of [resolving json-schema $ref](https://github.com/raml-org/typesystem-ts/blob/master/tests/jsonTests.ts#L7-L12). However [an additional step](https://github.com/raml-org/typesystem-ts/blob/master/tests/contentprovider.ts#L38-L128) seems to be required in order to make this work. This should either be abstracted (provide a default ContentProvider?) or documented.

Related: https://github.com/raml-org/raml-js-parser-2/issues/481 https://github.com/mulesoft/api-workbench/issues/314

**Comment by ddenisenko** [comment]
Lets handle this in raml-org/raml-js-parser-2#481 ticket to avoid duplications.
