### ISSUE TITLE
properties with in-line types does not validate 

### ISSUE THREAD

**Issue by jstoiko** [raml-org/typesystem-ts#83]
```
var ts = require('raml-typesystem').loadType({ type: [ 'string', 'integer' ] })
var result = ts.validate('string')
// result.isOk() is true
result = ts.validate(1)
// but here, result.isOk() is false
```

**Comment by ddenisenko** [comment]
The type `{ type: [ 'string', 'integer' ] }` is not valid itself, you can check this by running `ts.validateType()`. 

Here is the spec quote: `it is not allowed to inherit from different kind of primitive types, for example [ number, string ]`

**Comment by jstoiko** [comment]
my bad. I was looking to test union types, not multiple inheritance types.

this works:
```
var ts = require('raml-typesystem').loadType({ type: [ 'string | integer' ] })
var result = ts.validate('string')
// result.isOk() is true
result = ts.validate(1)
// result.isOk() is true
```
